### ISSUE TITLE
go ahead!

### ISSUE THREAD

**Issue by snikeguo** [UbiquityDotNET/Llvm.Net#1]
For LLVM.NET,although I can not help anything(I do not understand LLVM)..but I am looking forward to the development of this project, because I am looking forward to using C# to write microcontroller program, all embedded engineers are looking forward to it! go ahead!

**Comment by smaillet** [comment]
Well I don't know about All embedded engineers 😉  But I know a few, myself included. Once I get all the building blocks moved into this org and building correct for V5.0 I'll bring in the rest of the pieces for the AOT compilation as it stands.
