### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by AndyFraserABZ** [UbiquityDotNET/Llvm.NET#11]
I get the following error when I try and build the solution.

Error	MSB4030	"25/10/2017 10:20:57" is an invalid value for the "TimeStamp" parameter of the "GetBuildIndexFromTime" task. The "TimeStamp" parameter is of type "System.DateTime".	MultiPlatformBuild	C:\VS2017\Projects\Llvm.NET-master\BuildOutput\packages\CSemVer.Build.Tasks.1.0.0-alpha.2--ci-REL.194F4984\build\CSemVer.Build.Tasks.targets	117	

Any thoughts ?

Andy

**Comment by smaillet** [comment]
Hmm, looks like a bug in the CSemVer build task not accounting for localization of the date/time. If you temporarily set your date/time region settings to US does it work? I have an update planned on that build task I've been planning so I can hit this one as well. I'll need to look into how I can force that on the AppVeyor builds. We already switch the language to catch any assumptions on framework specific language strings.

**Comment by AndyFraserABZ** [comment]
I actually just replaced the macro in the targets file directly thus:

TimeStamp="10/25/2017 10:20:30"

This got me past the error I noted though I do get a bunch of compile warnings and errors that I am going to have to look through.

Andy

**Comment by smaillet** [comment]
FYI you can also get the CI builds from the AppVeyor Nuget feed at: https://ci.appveyor.com/nuget/Ubiquity.Llvm.NET

**Comment by smaillet** [comment]
This should be fixed now, the build tasks were updated to force a well known locale independent representation of the time stamp.
