### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by andyjansson** [UbiquityDotNET/Llvm.NET#117]
Hi, 

Is this project still maintained?

**Comment by smaillet** [comment]
Yes, work is on going for LLVM 10 right now. Beyond support of a new version of LLVM the big ticket items will be full use of GitHub Actions to build the LLVM libraries, which will ultimately obsolete the [Llvm.Libs](https://github.com/UbiquityDotNET/Llvm.Libs) project and clumsiness of publishing the libs as a zip etc... Instead the libs will build directly in this project and there won't be a need to maintain a build and lib download to support automated builds.

**Comment by andyjansson** [comment]
That's great news. I've been looking for .NET bindings for LLVM and at face value this project does seem to be everything I've wanted. While there are other projects in the same space, even when backed by reputable organisations, they've all ended up being neglected. I do have some concerns for adoption which I'm hoping you'll be able to alleviate:

1. Who are the people maintaining this project? Are they attached to any organisations?

2. While I understand that it might be hard to predict what the future might hold, it would be great to know if the team in it for the long run, i.e. that the project isn't going anywhere. 

3. Will you publish the packages to the official NuGet feed?

**Comment by smaillet** [comment]
I am the team at this stage, I'm perfectly open to additional contributors but, sadly, it isn't an area that attracts a lot of aid. I do intend to keep it going. Though I sometimes get swamped with real world and skip an LLVM release or get heavy on a project, not yet public, that uses Llvm.NET. While I do work at Microsoft at present and there is a history of this in use there, it is not actively maintained by or for my employer. (The future is, of course, fluid, but there are no plans at this time)

I can publish to official NuGet feed, that's been on my plan for a while now. There are two options, just release the current 8.0 bits or wait for the LLVM 10 binaries. (LLVM 10 is currently in RC state so the .NET projection shouldn't be too far behind it.) I'd entertain arguments either way... ;)

**Comment by andyjansson** [comment]
Great, thank you for taking the time to answer my questions.

**Comment by smaillet** [comment]
Public NuGet release of v8.0.0 is available now that the GH Actions build integration is complete. LLVM10 work is underway. It doesn't appear to contain major disruptive changes so it will hopefully not be long after the final release of LLVM10 when a first alpha is ready for LLVM.NET
