### ISSUE TITLE
Make unconstructable constructors internal?

### ISSUE THREAD

**Issue by andyjansson** [UbiquityDotNET/Llvm.NET#159]
Hi, 

I was looking at `DebugStructType` and and noticed several constructors which seemingly can't be called outside of the assembly, or at least not without creating custom concretions of some interfaces. This left me thinking that maybe these constructors (and others like it) should be marked as `internal` as they're probably not intended to be called by the consumer anyway?

Just a thought.

**Comment by smaillet** [comment]
Can you be more specific on that? All of the constructors are callable from application code.

**Comment by andyjansson** [comment]
Oh. Guess I'm stupid and missed it. `DebugStructType` itself implements `IStructType`. At first gander, I only saw `StructType`, which is `internal`. Disregard!

**Comment by smaillet** [comment]
It's worth noting that DebugStructType isn't the only implementation of IStructType. The internal StructType implements it as well, while that is an internal type you can create instances via Context.CreateStructType().
