### ISSUE TITLE
DebugStructType for anonymous structures?

### ISSUE THREAD

**Issue by andyjansson** [UbiquityDotNET/Llvm.NET#188]
Hi, 

I was looking at the changes made in #185 which now allows for the [creation of anonymous structures](https://github.com/UbiquityDotNET/Llvm.NET/blob/develop/src/Ubiquity.NET.Llvm/Context.cs#L420). However, when looking at [`DebugStructType`](https://github.com/UbiquityDotNET/Llvm.NET/blob/develop/src/Ubiquity.NET.Llvm/DebugInfo/DebugStructType.cs) I couldn't find a constructor which didn't require it to be named \[[1](https://github.com/UbiquityDotNET/Llvm.NET/blob/develop/src/Ubiquity.NET.Llvm/DebugInfo/DebugInfoBuilder.cs#L1434)]\[[2](https://github.com/UbiquityDotNET/Llvm.NET/blob/develop/src/Ubiquity.NET.Llvm/DebugInfo/DebugInfoBuilder.cs#L656)]. Is this an oversight or am I simply going about it the wrong way?

**Comment by smaillet** [comment]
String.Empty is valid (e.g. it is not null) this is a general design pattern for the changes supporting nullable reference types in v10.0.* to avoid null refs when plausible. Unfortunately, documentation is the only way to indicate if string.Empty is valid or not (or if whitespace is valid). null is used when there is a meaning for null that is distinct from any other instance. (i.e. in LLVM debug data void is represented as null and there is no no-null representation of the void type.)

**Comment by andyjansson** [comment]
Ah, cool. I see now that the version on NuGet uses `ValidateNotNullOrWhiteSpace`. I didn't realise that this had changed. Any estimate on when the next beta will land so I can start taking advantage of these features? :)

**Comment by smaillet** [comment]
Actually, there is a bug to be fixed on this as Context.CreateStructType() has ValidateNotNullOrWhiteSpace(). I'm hoping to take these changes to make another release shortly. I'm being a bit cautious with the 10 release as there are a lot of breaking changes (They are individually small and generally easy to handle but it is a Major update)
