### ISSUE TITLE
[BUG] - Error occurred while restoring NuGet packages: The local source 'BuildOutput\Nuget' doesn't exist

### ISSUE THREAD

**Issue by spacehamster** [UbiquityDotNET/Llvm.NET#195]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]` to mark an item as 'checked'

**.NET Framework Used:**

- [ ] .NET Core 3.0.0
- [ ] .NET Core 3.1.0
- [ ] Something else

**OS Environment:**

- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

OS Version: `Windows 10 Pro Version 2004`

**I have already...**

- [X] Reproduced the problem using the latest stable release.
- [ ] Reviewed the [documentation](https://ubiquitydotnet.github.io/Llvm.NET/).
- [X] Reviewed the [current issues](https://github.com/UbiquityDotNET/Llvm.NET/issues) to check that the issue isn't already known.

**Description:**

Building from src\Ubiquity.NET.Llvm.sln produces the following output
```
1>------ Build started: Project: Ubiquity.NET.Llvm, Configuration: Debug Any CPU ------
Error occurred while restoring NuGet packages: The local source 'C:\Files\Code\LLVM\Llvm.NET\BuildOutput\Nuget' doesn't exist.
1>C:\Program Files\dotnet\sdk\5.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1004: Assets file 'C:\Files\Code\LLVM\Llvm.NET\BuildOutput\Intermediate\Ubiquity.NET.Llvm\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "Ubiquity.NET.Llvm.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
Manually creating the folder `BuildOutput\Nuget` allows Llvm.NET to successfully build.

**Steps to reproduce the problem:**
* Create a fresh clone of the project
* Open src\Ubiquity.NET.Llvm.sln with Visual Studio 2019
* Try to build project Llvm.NET
- [ ] Reviewed the [documentation](https://ubiquitydotnet.github.io/Llvm.NET/).
- [ ] Included Sample code or link to repository/gist to reproduce the bug (This is the fastest way to a resolution as it reduces the time to reproduce the problem. The smaller the sample is the better.) 
      
**Expected Behavior**

Expected to build without errors.

**Actual Behavior**

Received build error.

**Additional context**

**Comment by smaillet** [comment]
You must run the Build-all.ps1 script first before trying to open the solution. I've added a WIKI page to help explain the build requirements better. Unfortunately, numerous limitations of VS and the components this code base relies on make it impossible to use a simple single solution file for everything.
