### ISSUE TITLE
[Feature] - Create MemoryBuffer from byte array

### ISSUE THREAD

**Issue by spacehamster** [UbiquityDotNET/Llvm.NET#196]
**Is your feature request related to a problem? Please describe.**
The only way to create a BitcodeModule from memory appears to be to write the memory to a file, create a MemoryBuffer from a file, and then load the BitcodeModule from the newly created MemoryBuffer. Ideally the memory could be fed directly to the MemoryBuffer.

**Describe the solution you'd like**
A new constructor added to MemoryBuffer that takes a byte array (`byte[]`) and a buffer name (`string`) and internally calls `LLVMCreateMemoryBufferWithMemoryRangeCopy`

**Describe alternatives you've considered**
Writing data to a file and then loading from a file.

**Additional context**
The signature for LLVMCreateMemoryBufferWithMemoryRangeCopy doesn't seem right, I would have expected either a byte array or a pointer, not a string for raw data.

**Comment by smaillet** [comment]
Indeed, it looks like the [Bindings configuration](https://github.com/UbiquityDotNET/Llvm.NET/blob/develop/src/Interop/LlvmBindingsGenerator/bindingsConfig.yml) for the interop layer doesn't have the mapping for that function. (For reasons not yet known the code that is supposed to catch theses sorts of things in LlvmBindingsGenerator, isn't catching this case...)

**Comment by smaillet** [comment]
While the bindings for that LLVM function are indeed incorrect (Working on a fix for that) I'm confused on the scenario you are trying to accomplish here. You can use [BitCodeModule.LoadFrom](https://ubiquitydotnet.github.io/Llvm.NET/current/api/Ubiquity.NET.Llvm.BitcodeModule.LoadFrom.html) to load a memory buffer into a bitcode module, and you can use [BitCodeModule.WriteToBuffer](https://ubiquitydotnet.github.io/Llvm.NET/current/api/Ubiquity.NET.Llvm.BitcodeModule.WriteToBuffer.html) to write an existing module into a buffer. 

So I'm confused on what scenarios you'd have an arbitrary blob of memory (as a byte[]) for a bit code module that wasn't read from a file? Where would you get the byte[] from if not reading it from a file?
