### ISSUE TITLE
Hyperlink leads to unrelated site

### ISSUE THREAD

**Issue by tymokvo** [UbiquityDotNET/Llvm.NET#223]
https://github.com/UbiquityDotNET/Llvm.NET/blob/54789d02479e2650f8520e392905581d381f2bf2/README.md?plain=1#L29

Hello, was just reading through the readme and noticed that the line above is currently linking to `netmf.com` which passes through a 301 redirect chain that ends up at `https://www.prfmnews.com/` which doesn't seem to be related.

**Comment by smaillet** [comment]
Interesting, nice catch! Looks like that old site has expired the name registration and squatters picked it up. It should probably point to the GitHub site as that will be pretty stable.
