### ISSUE TITLE
Build scripts failing

### ISSUE THREAD

**Issue by grahamehorner** [UbiquityDotNET/Llvm.NET#80]
Can't find 7-zip command line executable
At C:\Users\local.dev\source\repos\nanoFrameworkCore\Llvm.NET\buildutils.ps1:297 char:9
+         throw "Can't find 7-zip command line executable"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Can't find 7-zip command line executable:String) [], RuntimeException
    + FullyQualifiedErrorId : Can't find 7-zip command line executable

**Comment by smaillet** [comment]
That's not a bug. The build scripts require 7-zip to decompress the published LLVM libs. (7zip has the best compression ratio for the libs minimizing the download size). The instructions could be updated to list that as a requirement, though
